# 1. NUMPY BASICS

In [ ]:
import numpy as np
x = [5, 4, 5, 6, 8]  # 0 dimensional array

y = np.array(x)
y

array([5, 4, 5, 6, 8, 9])

In [ ]:
x = [[2, 5], [1, 9]]
y = np.array(x)
y

array([[2, 5],
       [1, 9]])

In [ ]:
x = [[4, 7, 1], [3, 6, 5], [1, 9, 3]]
y = np.array(x)
y

array([[4, 7, 1],
       [3, 6, 5],
       [1, 9, 3]])

In [ ]:
x = [[2, 3, 5, 6, 7], [1, 4, 8, 2, 9], [6, 4, 5, 6, 4], [2, 6, 3, 1, 9]]
y = np.array(x)
y

array([[2, 3, 5, 6, 7],
       [1, 4, 8, 2, 9],
       [6, 4, 5, 6, 4],
       [2, 6, 3, 1, 9]])

In [ ]:
y.shape

(4, 5)

In [ ]:
type(x)

list

In [ ]:
type(y)

numpy.ndarray

In [ ]:
z = np.array([[1, 3, 4], [4, 5, 6]])
z

array([[1, 3, 4],
       [4, 5, 6]])

In [ ]:
y.shape

(3, 4)

In [ ]:
type(x)

list

In [ ]:
type(y)

numpy.ndarray

In [ ]:
a = np.array([[2.0, 3, 4], [2, 9, 10]])

a.dtype

dtype('float64')

In [ ]:
print(a)

[[ 2.  3.  4.]
 [ 2.  9. 10.]]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
import numpy as np
# Define a 1D array == Vector

arrr = np.array([1])  # No dimension

arr1 = np.array([1, 2, 4, 5]) # 1 dimenson

# Define a 2D array == matrix
arr = np.array([[1, 2, 3], [8, 4, 5]]) # 2 dimension
# Print the array
print(arr1)
print(arr)

[1 2 4 5]
[[1 2 3]
 [8 4 5]]


In [ ]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax
import numpy as np

# Let's define a one-dimensional array
my_list = [10, 20, 50, 60, 70]
my_list

x = [[1,2,4], [2,4,6]]

In [ ]:
# Let's create a numpy array from the list "my_list"
x = np.array(x)
x

array([[1, 2, 4],
       [2, 4, 6]])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
# Multi-dimensional (Matrix definition)
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

In [ ]:
x = [[10, 2, 4, 5, 6, 20], [11, 2, 5, 6, 8, 9]]

import numpy as np
x = np.array(x)
x

array([[10,  2,  4,  5,  6, 20],
       [11,  2,  5,  6,  8,  9]])

In [ ]:
x = np.array([[2, 5, 7], [4, 9, 10], [3, 5, 10]])
x

array([[ 2,  5,  7],
       [ 4,  9, 10],
       [ 3,  5, 10]])

**MINI CHALLENGE #1:**
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7]
[20 5 6 9]]
```

In [ ]:
x = np.array([[4, 6, 8, 7], [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

In [ ]:
x.shape

(2, 4)

In [ ]:
x = [[4, 6, 8, 7], [20, 5, 6, 9]]
x = np.array(x)
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

In [ ]:
x = np.array([[4, 6, 8, 7], [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS

In [ ]:
y = np.random.rand(4,5)
y

array([[0.14166909, 0.60743549, 0.91211348, 0.3716273 , 0.72844518],
       [0.86100564, 0.34579253, 0.10542317, 0.36951562, 0.39617023],
       [0.16029299, 0.38111631, 0.21783776, 0.94958783, 0.7721889 ],
       [0.37410622, 0.48681202, 0.13455922, 0.10219896, 0.71867092]])

In [ ]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(3, 3)
x

array([[0.25465327, 0.82567761, 0.41724599],
       [0.141411  , 0.45663731, 0.9801989 ],
       [0.34814249, 0.02729588, 0.97025475]])

In [ ]:
# you can create a matrix of random number as well
x = np.random.rand(10, 10)
x

array([[0.16955839, 0.65667663, 0.23472973, 0.52468198, 0.12557623,
        0.49454709, 0.65031811, 0.97989738, 0.27436362, 0.08943013],
       [0.94552635, 0.24944664, 0.34621043, 0.43021377, 0.75358787,
        0.75260174, 0.06786495, 0.80591877, 0.68024578, 0.86849589],
       [0.39816701, 0.80363784, 0.88689166, 0.82829527, 0.98899778,
        0.79867339, 0.62688247, 0.14412778, 0.31319826, 0.4352495 ],
       [0.79801384, 0.11054788, 0.62199315, 0.30564487, 0.08905196,
        0.48338025, 0.77265405, 0.58576557, 0.69895833, 0.27363243],
       [0.41913878, 0.44058698, 0.85707438, 0.7566107 , 0.22485787,
        0.73884097, 0.40155185, 0.09570741, 0.36357556, 0.32473543],
       [0.64764164, 0.2411693 , 0.57689615, 0.79336403, 0.99737858,
        0.74924868, 0.63658291, 0.0344297 , 0.55421345, 0.07673638],
       [0.218474  , 0.23837162, 0.9103716 , 0.08662899, 0.45198129,
        0.32966071, 0.32491868, 0.30025093, 0.24503328, 0.53748129],
       [0.36949379, 0.61393087, 0.9122526

In [ ]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(3, 3)
x

array([[ 0.78375818,  1.39963862, -0.25653417],
       [ 0.73225974,  0.85011081,  0.28240454],
       [ 1.16618366,  0.60794171,  0.70461105]])

In [ ]:
x = np.random.randint(10, 51, (4, 5))
x

array([[12, 49, 17, 29, 42],
       [26, 36, 30, 25, 44],
       [39, 49, 37, 22, 48],
       [22, 12, 21, 27, 41]])

In [ ]:
x = np.random.randint(0, 11, (3,3))
x

array([[ 4,  7, 10],
       [ 8, 10,  1],
       [ 1,  2,  5]])

In [ ]:
x = np.random.randint(0, 5, (3,4))
print(x)

[[3 3 2 0]
 [1 3 2 3]
 [0 1 1 4]]


In [ ]:
# Generate random uniformly distributed values, normal distributed values and random integers.
# Size: 3x3, 4x4, 2x3

In [ ]:
# Uniformly distributed values

x = np.random.rand(3,3)

# Normal distributed values

y = np.random.randn(3,3)

# Random integers

z = np.random.randint(0, 10, (3,3))

print(x)
print(y)
print(z)

[[0.82987062 0.34470121 0.26326645]
 [0.98417108 0.17685851 0.02476351]
 [0.00492287 0.7304239  0.42204942]]
[[-0.90137118 -2.39685233  0.54000947]
 [ 1.0833265   1.07740507 -0.06506952]
 [-0.05453326 -2.5358722   1.1479435 ]]
[[4 9 5]
 [2 4 1]
 [2 7 0]]


In [ ]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10, 5)
x

array([3, 7, 3, 9, 6])

In [ ]:
x = np.random.randint(2, 6, 5)
x

array([2, 5, 3, 4, 3])

In [ ]:
for i in range(1,20,1):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 101, 10)
x

array([73, 72, 76, 36, 31, 87, 44, 68, 34, 27])

In [ ]:
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [ ]:
len(x)

10

In [ ]:
x.reshape(3,5)

ValueError: ignored

In [ ]:
x = np.arange(1, 100, 10)
print(x)

[ 1 11 21 31 41 51 61 71 81 91]


In [ ]:
x = np.arange(1, 51, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [ ]:
x = np.arange(1, 51, 10)
x

array([ 1, 11, 21, 31, 41])

In [ ]:
x = np.array([2, 4, 5])
print(x)

[2 4 5]


In [ ]:
x = np.array([[2, 4, 5], [2, 4, 9]])
print(x)

[[2 4 5]
 [2 4 9]]


In [ ]:
len(x)

2

In [ ]:
x.shape

(2, 3)

In [ ]:
x = np.array([[2, 5, 7, 9], [1, 8, 3, 8], [3, 9, 2, 5]])
print(x)

[[2 5 7 9]
 [1 8 3 8]
 [3 9 2 5]]


In [ ]:
x.shape

(3, 4)

In [ ]:
x.reshape(2,6)

ValueError: ignored

In [ ]:
x = np.zeros((2,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x = np.eye(6,6)
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
x = np.full((3,3), 10)
x

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
x = np.arange(0, 20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
y = x.reshape(4,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a = np.arange(0, 50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [ ]:
b = a.reshape(5, 10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [ ]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(10, 100, 5)
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [ ]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(10,10)
print(x)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
x = np.ones((10,10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x = np.eye(2, dtype = float)
print(x)

[[1. 0.]
 [0. 1.]]


In [ ]:
# Array of ones
x = np.zeros((2,5), dtype = int)
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [ ]:
# Array of zeros
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np

x = int(input('Provide the upper boundary for the list of numbers '))

y = np.random.randint(0, x+1, 20)
y



Provide the upper boundary for the list of numbers 10


array([ 2,  8,  9,  6,  0,  2, 10, 10,  2,  2, 10,  9,  8,  3,  9,  1,  2,
        6,  6,  9])

In [ ]:
np.ones((3,20))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [ ]:
import numpy as np

x = int(input('Provide the upper boundary for the list of numbers '))

for i in range(1,x):
  y = np.random.rand(1,20)
print(y)

Provide the upper boundary for the list of numbers 10
[[0.52097974 0.17876585 0.45341854 0.57720457 0.60929229 0.96414984
  0.05336483 0.27588888 0.90246046 0.13627861 0.79965995 0.89324916
  0.89043474 0.06471775 0.44328094 0.73535905 0.81923164 0.76968295
  0.20386049 0.14448367]]


**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
import numpy as np

x = int(input('Provide a number '))

y = np.random.randint(0, x, (1,20))
print(y)

Provide a number 4
[[2 3 0 1 0 1 2 2 1 2 2 3 1 1 0 1 1 3 0 2]]


In [ ]:
import numpy as np

x = int(input('number'))

for i in range(0, x):
  y = np.random.randn(1, 20)

y

number10


array([[-1.47585083,  0.08561296, -1.18338349, -0.77858683, -1.64490605,
         0.32750043, -1.68906714, -0.03408099, -1.41960666, -0.42665042,
         0.0522478 ,  1.16737989, -0.19714283,  0.02413745,  0.4777778 ,
        -1.24785038,  0.12008788,  0.3526426 , -0.63354895,  1.0536313 ]])

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value: 10


array([7, 4, 2, 5, 9, 6, 3, 8, 5, 3, 2, 9, 2, 8, 8, 5, 6, 1, 2, 2])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [1]:
import numpy as np

x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
y = x.reshape(4,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
y.reshape(1,20)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [8]:
# To get the minimum number in a matrix

np.min(y)

1

In [9]:
np.max(y)

20

In [10]:
y.min()

1

In [11]:
y.max()

20

In [ ]:
# Let's define a one-dimensional array
my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [ ]:
# Get Length of a numpy array
len(x)

1

In [ ]:
x[-1]

90

In [24]:
y = np.array([[1.0, 2.0, 4.0], [2.0, 6.0, 7.0], [4.0, 7.0, 9.0], [5.0, 7.0, 9.0], [4, 6, 8]])
y

array([[1., 2., 4.],
       [2., 6., 7.],
       [4., 7., 9.],
       [5., 7., 9.],
       [4., 6., 8.]])

AttributeError: ignored

In [ ]:
type(y)

numpy.ndarray

In [ ]:
# Get shape
y.shape

(5, 3)

In [ ]:
y.dtype

dtype('float64')

In [ ]:
type(y)

numpy.ndarray

In [15]:
x = np.array([[2.0, 4, 7], [4, 8, 9], [6, 4, 5], [3, 6, 7], [7, 8, 9], [4, 2, 8]])
x

array([[2., 4., 7.],
       [4., 8., 9.],
       [6., 4., 5.],
       [3., 6., 7.],
       [7., 8., 9.],
       [4., 2., 8.]])

In [18]:
x[2:5, 1:3]

array([[4., 5.],
       [6., 7.],
       [8., 9.]])

In [17]:
x[0:2, 1:3]

array([[4., 7.],
       [8., 9.]])

In [13]:
x.shape

(3, 3)

In [ ]:
x[0][1]

4.0

In [ ]:
x.dtype

dtype('float64')

In [ ]:
# Obtain the datatype
y.dtype

dtype('float64')

In [ ]:
y.shape

(4, 3)

In [ ]:
y[0]

array([1., 2., 4.])

In [ ]:
x = np.array([[2, 4, 5, 8], [4, 5, 7, 1], [4, 8, 4, 5], [5, 0, 3, 1]])

# Convert the above matrix to a 2x8 matrix

x.reshape(3,5 + 3)


ValueError: ignored

In [ ]:
# Reshape 1D array into a matrix
z = y.reshape(3,4)
print(y)
print(z)

[[1. 2. 4.]
 [2. 6. 7.]
 [4. 7. 9.]
 [5. 7. 9.]]
[[1. 2. 4. 2.]
 [6. 7. 4. 7.]
 [9. 5. 7. 9.]]


In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
a = np.array([[1, 5, 6], [5, 2, 9], [0, 3, -1]])
a

array([[ 1,  5,  6],
       [ 5,  2,  9],
       [ 0,  3, -1]])

In [ ]:
a.max()

9

In [ ]:
b = np.array([[-2, -3, -5], [0, 3, 4], [4, 8, 9]])
b

array([[-2, -3, -5],
       [ 0,  3,  4],
       [ 4,  8,  9]])

In [19]:
x = np.random.randint(1, 10, (5,5))
x

array([[4, 5, 9, 3, 7],
       [2, 8, 8, 5, 8],
       [8, 4, 5, 6, 2],
       [6, 2, 9, 4, 4],
       [9, 3, 8, 4, 6]])

In [21]:
np.min(x)

2

In [22]:
x.argmin()

5

In [23]:
x.argmax()

2

In [ ]:
b.argmin()

2

In [ ]:
abs(b)

array([[2, 3, 5],
       [0, 3, 4]])

In [ ]:
len(b)

2

In [ ]:
b.shape

(2, 3)

In [ ]:
b.argmin()

3

In [ ]:
x.max()

8

In [ ]:
x

array([[2, 4, 5, 8],
       [4, 5, 7, 1],
       [4, 8, 4, 5],
       [5, 0, 3, 1]])

In [ ]:
# Obtain the maximum element (value)
x.max()

8

In [ ]:
# Obtain the minimum element (value)
x.min()

0

In [ ]:
# Obtain the location of the max element
x.argmax()

3

In [ ]:
# Obtain the location of the min element
x.argmin()

13

In [ ]:
x = np.arange(300, 500, 10)
x

array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
       430, 440, 450, 460, 470, 480, 490])

In [ ]:
y = x.reshape(4,5)
y

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [27]:
x = np.arange(300,500, 10)
x

array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
       430, 440, 450, 460, 470, 480, 490])

In [28]:
len(x)

20

In [29]:
x.reshape(4,5)

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

In [ ]:
x = np.arange(300, 500, 10)
print(x)

[300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450 460 470
 480 490]


In [ ]:
len(x)

20

In [ ]:
y = x.reshape(4,5)
print(y)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


In [ ]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [ ]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values**

In [34]:
x = np.random.randint(-1000, 1000, (20,20))
x

array([[ 849, -799,  868, -900, -626,   70, -644,   74, -139, -709,  156,
        -895, -869, -413,  637,  897, -916,   20,   93, -783],
       [ 470, -288,  996,  350,  536,  911, -121, -221, -327,  829,  133,
         792,  256,   91, -812, -132, -598, -259, -911, -799],
       [-918,  187,  -37,  -11, -182,  853, -662,  156, -578,  690, -178,
        -105, -134, -339,  677,  -92,  328, -703,  -81, -721],
       [-276,  507, -663, -632, -602,  438,  567, -821,  364,  148, -687,
         714,  989,  295, -565,   90,  812,  479,   -2, -468],
       [-366, -501,  260,   27,  179,  -59,  914,  143, -433, -330, -681,
         864, -267,  497,  933,  766,   87,  609,  284,  186],
       [-150,  842,  741, -960,  168,  369, -418,   22,  286,   61, -123,
        -566, -390, -455,  641, -472,  345,   14, -400,   83],
       [ 208,  267,  147, -427, -289, -100, -964,  456,  444, -873, -913,
         739,  822, -831,   72,  403, -551,  295,  382, -283],
       [ 988, -995,  633, -799,  120,  17

In [35]:
np.max(x)

996

In [36]:
np.min(x)

-995

In [37]:
x.mean()

-41.745

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)

[[-556  273  908 -120  104 -683 -455  578   53  -78   20  601 -624  176
   447 -177 -695 -453 -979  770]
 [ 276 -752   93 -817  339  258   76 -800 -197  725 -638  -62  818  573
  -299  817  997  831  243  745]
 [-215  125  922 -321  864  913  191 -260  948  483  -23  907 -587  551
    75 -328  377 -715 -496 -548]
 [ 199  782 -440 -933 -497 -358 -574 -171 -186 -848  678 -814 -717 -139
   124  355  993  699 -162  813]
 [-117  -69 -857  316 -902  597  862  343  710 -684 -932   71 -568  415
   264 -668 -581 -101 -161 -299]
 [ 198  847   -4 -534 -226 -340 -355   -2  618  477 -246  117  313 -990
  -564 -360 -889 -747 -390  902]
 [-921  477 -712  124   64  385   -2 -608 -784 -648   52 -972 -418  530
   660  388  599  838  876  270]
 [ 105 -141  821  455 -627  460  197  864  517  -32  784  890 -224   57
  -922  770  825 -788   -9  360]
 [ -84 -118  992   -1  566  780 -948 -636 -637 -709 -364  441 -124  145
   929 -109  142  363 -387  206]
 [ 463  762 -202  870 -231  793  908  583  200  774 -66

In [ ]:
x.mean()

34.25

In [ ]:
x.mean()



-18.7775

In [ ]:
x = np.random.randint(-1000, 1000, (20,20))

print(x)

[[ 186  631  633  914 -946  641 -464  536 -469  680 -612  590  939  -14
   850  192 -210  563 -631  403]
 [-256 -334 -333 -611 -103 -881 -670  156  -62 -175 -546  686 -297 -494
  -315 -405 -767 -942 -572  455]
 [ 627  341 -936  374 -277  941 -378   41 -552 -237 -513  681  434  472
   188  -76  158  941  877 -611]
 [ 608 -656  164  223 -904 -558  905 -843  -57  222  668 -249  592 -458
   752  877 -681 -198  485 -173]
 [ 753  389 -311  501 -752 -329 -783  398 -488 -766 -558 -906 -617 -826
  -104  -74 -771 -713  985 -934]
 [-274 -408 -441 -746  849 -771  263 -564  463  827  423  415  -33 -895
  -912 -419  792   94  416   10]
 [-677  825  561 -793  872  626 -598 -276    5  106 -466 -346  892  246
   548 -103  653   38 -905 -471]
 [-491  914 -281 -160 -615  950 -917 -526 -539  153  686 -115  362  127
   880  636  659 -114 -384  -28]
 [-649 -163  674  411  -82  120 -250  745   57 -681 -897 -865 -351 -660
   348 -624 -830  660  369 -859]
 [ 504 -753 -549 -541  480   88  829  235 -388  717 -54

In [ ]:
import numpy as np
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[ 635  397  707  485 -116  149 -150  993  156 -900 -788 -329 -922 -675
  -205  621  213 -513   -2 -733]
 [ 495  604 -389  402 -221  611 -533 -318 -308  680  712   18  -21 -756
   210  896  483 -468 -299 -567]
 [ 607  828  813  425 -233  625  160   96  828 -181 -148  540 -202  342
  -206  581  -69  473  167 -364]
 [ 580  -64 -755 -769  745  923  957 -454 -395  -70  102  389 -995 -409
   842  779  259 -709 -905  786]
 [-859   -7  322 -773 -447 -243 -480 -660 -228 -448  387 -761  157  942
  -644  465  596 -435 -187 -607]
 [-416  645 -524  212  -12  224 -486  -48 -467 -951  133  267 -330 -778
  -520  677  574  858  248  914]
 [ 195  230 -581 -151   49 -997  385  837 -651 -588 -793 -879  441  -59
  -382 -677  695 -608  354  192]
 [ 605 -185  749  821  606 -349  299  745 -882 -837  301  933 -263  925
  -356  365  256  872    3  571]
 [ -63 -971  743  140 -165  228  818  901  631   39 -625  654  472  -27
  -928  517 -670  637  854 -358]
 [-834 -592 -615  950  357  805  480  471 -617 -979  36

# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x = np.array([[2, 3], [1, 6]])
y = np.array([[5, 8], [4, 1]])

a = abs(x-y)
a

array([[3, 5],
       [3, 5]])

In [54]:
a = np.random.randint(1,10, (2,4))
b = np.random.randint(1, 10, (4,2))

print(f'{a}, {b}')

[[3 3 9 5]
 [8 8 3 6]], [[1 3]
 [9 6]
 [8 3]
 [8 2]]


In [55]:
np.dot(a,b)

array([[142,  64],
       [152,  93]])

In [41]:
subtract = x - y
subtract

array([[-3, -5],
       [-3,  5]])

In [39]:
np.dot(x,y)

array([[22, 19],
       [29, 14]])

In [ ]:
x = np.array([[3, 1, 9], [5, 6, 7], [4, 3, 4]])
y = np.array([[4, 5, 6], [8, 8, 2], [2, 3, 7]])
print(x)
print(y)

[[3 1 9]
 [5 6 7]
 [4 3 4]]
[[4 5 6]
 [8 8 2]
 [2 3 7]]


In [ ]:
abs(x - y)

array([[1, 4, 3],
       [3, 2, 5],
       [2, 0, 3]])

In [58]:
a = np.array([[2, 4, 5], [5, 1, 2]])
b = np.array([[2, 3], [4, 5], [4, 8]])

In [60]:
b.T

array([[2, 4, 4],
       [3, 5, 8]])

In [ ]:
a = np.array([[2, 3], [4, 8]])
b = np.array([[1, 6], [2, 7]])

z = np.matmul(a, b)
print(z)

[[ 8 33]
 [20 80]]


In [ ]:
print(a.T)
print(a)

[[2 4]
 [3 8]]
[[2 3]
 [4 8]]


In [ ]:
np.matmul(a,b)

array([[ 8, 33],
       [20, 80]])

In [ ]:
x * y

array([[12,  5, 54],
       [40, 48, 14],
       [ 8,  9, 28]])

In [ ]:
np.dot(a,b)

array([[ 8, 33],
       [20, 80]])

In [ ]:
x = np.array([[2, 3, 7], [3, 9, 10]])
y = np.array([[4, 2], [6, 3], [9, 2]])

np.dot(x,y)

array([[ 89,  27],
       [156,  53]])

In [ ]:
print(a)
print(b)

[[2 3]
 [4 8]]
[[1 6]
 [2 7]]


In [ ]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
x

array([[3, 1, 9],
       [5, 6, 7],
       [4, 3, 4]])

In [61]:
x = np.array([[36, 9], [4, 81]])
x

array([[36,  9],
       [ 4, 81]])

In [62]:
np.sqrt(x)

array([[6., 3.],
       [2., 9.]])

In [ ]:
squared = x**2
squared

array([[ 9,  1, 81],
       [25, 36, 49],
       [16,  9, 16]])

In [ ]:
sqrt = np.sqrt(squared)
sqrt

array([[3., 1., 9.],
       [5., 6., 7.],
       [4., 3., 4.]])

In [ ]:
y

array([[4, 5, 6],
       [8, 8, 2],
       [2, 3, 7]])

In [ ]:
z = np.exp(y)
z

array([[  54.59815003,  148.4131591 ,  403.42879349],
       [2980.95798704, 2980.95798704,    7.3890561 ],
       [   7.3890561 ,   20.08553692, 1096.63315843]])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [63]:
x = np.array([3, 20, 30])
y = np.array([4, 6, 7])

z = x-y
ans = np.sqrt(np.sum(np.square(z)))
ans

26.94438717061496

In [ ]:
x = np.array([[3, 20, 30]])
y = np.array([[4, 6, 7]])

z = x - y

t = z.T

In [ ]:
import math

x = math.sqrt((3-4)**2 + (20-6)**2 + (30-7)**2)
x

26.94438717061496

In [ ]:
import numpy as np

x = np.array([[3, 20, 30]])
y = np.array([[4, 6, 7]])

In [ ]:
z = x - y

np.sqrt(np.sum(np.square(z)))

26.94438717061496

In [ ]:
a = np.dot(z, t)
print(a)

[[726]]


In [ ]:
d = np.sqrt(a)
print(d)

[[26.94438717]]


In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

In [ ]:


X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])

z = X - Y
distance = np.sqrt(np.sum(np.square(z)))
distance

26.94438717061496

In [ ]:
z

array([-1, 14, 23])

In [ ]:
z.T

array([-1, 14, 23])

In [ ]:
np.dot(z, z.T)

726

In [ ]:
np.sqrt(np.dot(z, z.T))

26.94438717061496

# 5. SLICING AND INDEXING

In [ ]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [ ]:
# Access specific index from the numpy array
x[1] = 80
x

array([20, 80, 50, 21, 15])

In [ ]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[1] = 10
x[2] = 20
x

array([20, 10, 20, 21, 15])

In [ ]:
# Broadcasting, altering several values in a numpy array at once
x[0:3] = 10
x

array([10, 10, 10, 21, 15])

In [ ]:
matrix = np.random.randint(1,10, (5,5))
matrix

array([[2, 9, 5, 6, 3],
       [6, 1, 8, 1, 8],
       [8, 2, 3, 8, 5],
       [4, 6, 8, 1, 7],
       [1, 3, 7, 3, 8]])

In [ ]:
matrix[3:, :] = 10
matrix

array([[ 2,  9,  5,  6,  3],
       [ 6,  1,  8,  1,  8],
       [ 8,  2,  3,  8,  5],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
d = np.array([[2, 4, 2], [5, 6, 7], [8, 3, 4]])
d

array([[2, 4, 2],
       [5, 6, 7],
       [8, 3, 4]])

In [ ]:
d[2]

array([8, 3, 4])

In [ ]:
d[1:, 1:]

array([[6, 7],
       [3, 4]])

In [ ]:
np.full((3,3), -2)

array([[-2, -2, -2],
       [-2, -2, -2],
       [-2, -2, -2]])

In [ ]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,20, (5, 5))
matrix

array([[18, 12, 16,  3, 14],
       [ 9,  8,  5, 14, 18],
       [10, 12, 13,  3, 10],
       [ 1,  6, 18, 16,  5],
       [ 2,  4,  8,  2, 19]])

In [ ]:
# Get a row from a mtrix
matrix[-1][-1]

6

In [ ]:
# Get one element
matrix[0][2]

4

In [ ]:
mini_matrix = matrix[-3:]
mini_matrix

array([[18, 16, 17,  3,  7],
       [ 1,  4,  9, 12,  3],
       [19, 17, 11, 17,  6]])

In [ ]:
mini_matrix = matrix[2:]
mini_matrix

array([[9, 2, 5, 2, 9],
       [8, 3, 3, 3, 8],
       [1, 1, 2, 1, 4]])

In [ ]:
matrix = np.random.randint(1,20, (5, 5))
matrix

array([[ 6, 17, 12, 10, 18],
       [11, 14, 17,  5,  2],
       [ 9,  9, 11, 17, 12],
       [13,  3,  9,  9,  1],
       [11, 15,  8,  2,  4]])

In [ ]:
mini_matrix = [matrix[:, 0],matrix[:, 2]]
print(mini_matrix)

[array([ 6, 11,  9, 13, 11]), array([12, 17, 11,  9,  8])]


In [ ]:
mini_matrix = matrix[:, -5]
mini_matrix

array([ 6, 11,  9, 13, 11])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [74]:
x = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [75]:
x[0:2, 3:] = x[0:2, 3:] * 2
x


array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [70]:
x[-2][-1] = -1
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, -1],
       [-1, -1, -1, -1, -1]])

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [ ]:
X[-1] = -1
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [ ]:
X[:2, -2]

In [ ]:
X[:2, -2:] = y
X[:2, -2:] = y*2
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [ ]:
y = X[0:2, -2:]
y*2

array([[-4, -8],
       [-6, -4]])

In [ ]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [ ]:
y = np.eye(2,2)
y

array([[1., 0.],
       [0., 1.]])

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
import numpy as np
matrix_A = np.array([[1,0,9,2,2],[3,23,4,5,1],[0,2,3,4,1], [1,4,6,8,5]])
matrix_A




array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1],
       [ 1,  4,  6,  8,  5]])

In [ ]:
np.ones_like(matrix_A)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
array_empty_like = np.empty_like(matrix_A)
matrix_A

In [ ]:
# Shape and type are like the prototype.
# If we want to override this, we can define dtype and shape and pass different values (but why even use empty_like then).

print(array_empty_like)




[[101155756098798               0    210453397549    193273528368
     227633266736]
 [   206158430292    249108103223    214748364850    206158430266
     197568495669]
 [   210453397558    206158430265    231928234040 137322989355098
              128]]


In [ ]:
array_0s_like = np.zeros_like(matrix_A)
print(array_0s_like)

# We have corresponding functions for 1s and full as well.

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
import numpy as np


empty_array = np.empty(10)
empty_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
zeros_array = np.zeros(10)

zeros_array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ones_array = np.ones(10)

ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
twos_array = np.full((2,3), 3)

twos_array

array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.amin(twos_array)

3

In [ ]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# 6. ELEMENTS SELECTION (CONDITIONAL)

In [76]:
import numpy as np
x = np.random.randint(-5,10, (5, 5))
x

array([[ 7, -3,  3,  9,  9],
       [-4,  8, -3,  0,  7],
       [-2,  5, -2,  8,  9],
       [ 0,  5,  1,  6, -1],
       [-2, -1,  1, -3,  5]])

In [84]:
y = x[x % 2 == 0]

array([8, 8, 6])

In [ ]:
y = x[x < 0]
y

array([-3, -2, -4, -4, -4, -2])

In [ ]:
y = x[x > 4]
y

array([7, 6, 5, 5, 6, 7, 7, 8, 8, 5, 7, 9])

In [ ]:
a = np.array([1, 2, 4])

In [ ]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0], [5,7,3,4,6]])
matrix_B



array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0],
       [5, 7, 3, 4, 6]])

In [ ]:
np.maximum.reduce(matrix_B, axis = 0)

array([4, 6, 6, 8, 4])

In [ ]:
matrix_B[1::2, 0::1]

array([[3, 6, 6, 7, 4],
       [5, 7, 3, 4, 6]])

In [105]:
x = np.random.randint(1, 10, (6,6))
x

array([[4, 3, 4, 8, 9, 7],
       [7, 6, 4, 1, 6, 4],
       [6, 6, 2, 4, 3, 7],
       [6, 8, 7, 2, 5, 2],
       [1, 3, 1, 5, 2, 2],
       [4, 5, 9, 8, 9, 9]])

In [106]:
np.cov(x)

array([[ 6.16666667, -2.26666667, -1.06666667, -4.8       ,  1.46666667,
         3.66666667],
       [-2.26666667,  4.66666667,  1.06666667,  3.6       , -2.26666667,
        -2.66666667],
       [-1.06666667,  1.06666667,  3.86666667, -1.        ,  0.13333333,
        -2.26666667],
       [-4.8       ,  3.6       , -1.        ,  6.4       , -1.8       ,
        -2.8       ],
       [ 1.46666667, -2.26666667,  0.13333333, -1.8       ,  2.26666667,
         0.26666667],
       [ 3.66666667, -2.66666667, -2.26666667, -2.8       ,  0.26666667,
         5.06666667]])

In [107]:
np.var(x)

6.193672839506173

In [109]:
np.std(x)

2.4887090708851796

In [110]:
np.corrcoef(x)

array([[ 1.        , -0.42253144, -0.21844148, -0.76405745,  0.39229462,
         0.65597158],
       [-0.42253144,  1.        ,  0.25110593,  0.65873255, -0.69693205,
        -0.5484085 ],
       [-0.21844148,  0.25110593,  1.        , -0.2010211 ,  0.04503773,
        -0.51210395],
       [-0.76405745,  0.65873255, -0.2010211 ,  1.        , -0.47259453,
        -0.49170755],
       [ 0.39229462, -0.69693205,  0.04503773, -0.47259453,  1.        ,
         0.07868895],
       [ 0.65597158, -0.5484085 , -0.51210395, -0.49170755,  0.07868895,
         1.        ]])

In [102]:
# At axis 0, we are considering the columns
print(np.amax(x, axis = 0))
print(np.amin(x, axis = 0))

[9 8 9 8 9 9]
[1 1 2 2 3 5]


In [103]:
# At axis 1, we are considering the rows
print(np.amax(x, axis = 1))
print(np.amin(x, axis = 1))

[9 9 8 9 8 8]
[1 1 1 2 2 3]


In [96]:
x[:, 0::2]

array([[6, 9, 1],
       [9, 9, 3],
       [1, 2, 6],
       [7, 1, 8],
       [3, 1, 5],
       [1, 2, 7]])

In [ ]:
np.mean(x)

2.6832815729997477

In [ ]:
np.median(x)

In [ ]:
150/25

6.0

In [ ]:
np.maximum.reduce(x, axis = 1)

array([8, 8, 8, 8, 9])

In [ ]:
y = np.arange(1, 10)
y = y.reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = y[y % 2 == 0]
x

array([2, 4, 6, 8])

In [ ]:
new_matrix = x[x % 2 == 1]
new_matrix

array([1, 3, 5, 7, 9])

In [ ]:
import numpy as np


empty_array = np.amin(matrix, axis = 1)
empty_array

array([1, 2, 3, 4, 2])

In [ ]:
new_matrix = matrix[matrix > 3]
new_matrix

array([7, 9, 8, 9, 5, 8, 8, 5, 6, 7, 8, 9, 7, 9, 8])

In [ ]:
new_matrix = matrix[matrix % 2 == 0]
new_matrix

array([2, 8, 8, 8, 6, 8, 8, 2])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

In [ ]:
X[X < 0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [ 3,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [ ]:
X[X % 2 == 1] = 25
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

In [ ]:
X[X  < 0] = 0
X[X % 2 == 1] = 25

In [ ]:
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:**
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7]
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value: 1000


array([706, 600, 225, 324, 964, 965, 281, 559, 536, 764, 950, 514, 997,
        39, 402, 606, 659, 665,  73, 663])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [ ]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values**

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[-696  963  484 -788  940  206  144  -34 -251 -943  548 -693  441 -651
  -278 -564  805  734 -486 -419]
 [-788 -242  725  133  452  631  659  291 -118  233  280 -157   41    9
  -572 -950  127 -940 -554 -149]
 [ 125  904  -96  662 -840 -731  598  153  317  858 -504  829 -737  269
   908 -995  -53  482   89   34]
 [  35  469 -157 -981 -462 -669 -222   97  332  840  768  824 -935 -342
   153  987  914  129  409  350]
 [ 339  456 -475  184  984   89 -698 -926  779  967  868  329   55 -637
   290  805 -966 -399    2 -845]
 [  42 -861  556  147  -32 -645  927  220 -428  565  549  134  433  -11
  -403 -465 -559  874  755 -246]
 [ 625  768  759  352  214  985  366 -307 -514  496  611   82 -778 -220
  -174  646  363 -537  451  925]
 [ 476 -354  722  968 -358 -891 -957    9  566 -892  779    0 -853   96
   116  914 -801 -265  614  923]
 [ 828   91  111   72  987 -635    2 -342 -700  -90 -537  841  246  162
   174  630   22  734 -180 -786]
 [ 726 -194 -358  351  221 -199  591  656 -992  845 -24

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


(5, 5)

In [ ]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

In [1]:
import numpy as np
x = np.random.randint(1,50, (6,8))
x

array([[19,  8,  8, 30, 41, 21, 36, 25],
       [43, 14, 20, 35, 25, 18, 26, 47],
       [24, 25, 24, 35,  3, 35, 21,  9],
       [26, 33,  6, 28, 15, 38,  9, 33],
       [15, 41, 45, 33, 44, 21, 11, 27],
       [42, 49, 48,  5, 11, 40, 14, 25]])

In [2]:
x[1] = 0

In [3]:
x

array([[19,  8,  8, 30, 41, 21, 36, 25],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [24, 25, 24, 35,  3, 35, 21,  9],
       [26, 33,  6, 28, 15, 38,  9, 33],
       [15, 41, 45, 33, 44, 21, 11, 27],
       [42, 49, 48,  5, 11, 40, 14, 25]])

In [5]:
x[:, 2] = 0

In [6]:
x

array([[19,  8,  0, 30, 41, 21, 36, 25],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [24, 25,  0, 35,  3, 35, 21,  9],
       [26, 33,  0, 28, 15, 38,  9, 33],
       [15, 41,  0, 33, 44, 21, 11, 27],
       [42, 49,  0,  5, 11, 40, 14, 25]])

In [10]:
x[5][7] = 60

In [11]:
x

array([[19,  8,  0, 30, 41, 21, 36, 25],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [24, 25,  0, 35,  3, 35, 21,  9],
       [26, 33,  0, 28, 15, 38,  9, 33],
       [15, 41,  0, 33, 44, 21, 11, 27],
       [42, 49,  0,  5, 11, 40, 14, 60]])

In [13]:
x[-1,-1] = 6


In [14]:
x

array([[19,  8,  0, 30, 41, 21, 36, 25],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [24, 25,  0, 35,  3, 35, 21,  9],
       [26, 33,  0, 28, 15, 38,  9, 33],
       [15, 41,  0, 33, 44, 21, 11, 27],
       [42, 49,  0,  5, 11, 40, 14,  6]])

In [16]:
x[x % 2 == 1] = -1

In [17]:
x

array([[-1,  8,  0, 30, -1, -1, 36, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [24, -1,  0, -1, -1, -1, -1, -1],
       [26, -1,  0, 28, -1, 38, -1, -1],
       [-1, -1,  0, -1, 44, -1, -1, -1],
       [42, -1,  0, -1, -1, 40, 14,  6]])

In [18]:
np.mean(x)

6.520833333333333

In [19]:
np.max(x)

44

In [20]:
np.min(x)

-1

In [22]:
x.argmax()

36

In [23]:
x.argmin()

0

In [24]:
np.std(x)

13.884928254726018

In [25]:
np.var(x)

192.7912326388889

In [26]:
np.cov(x)

array([[235.92857143,   0.        , -36.07142857,  -5.14285714,
        -63.92857143, -69.60714286],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [-36.07142857,   0.        ,  77.35714286,  52.        ,
        -21.21428571, 104.03571429],
       [ -5.14285714,   0.        ,  52.        , 277.14285714,
        -78.71428571, 211.        ],
       [-63.92857143,   0.        , -21.21428571, -78.71428571,
        251.64285714, -87.75      ],
       [-69.60714286,   0.        , 104.03571429, 211.        ,
        -87.75      , 339.125     ]])

In [27]:
np.corrcoef(x)

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


array([[ 1.        ,         nan, -0.26700713, -0.02011233, -0.26236894,
        -0.24608415],
       [        nan,         nan,         nan,         nan,         nan,
                nan],
       [-0.26700713,         nan,  1.        ,  0.35514139, -0.15204982,
         0.64232132],
       [-0.02011233,         nan,  0.35514139,  1.        , -0.29806392,
         0.68825711],
       [-0.26236894,         nan, -0.15204982, -0.29806392,  1.        ,
        -0.3003827 ],
       [-0.24608415,         nan,  0.64232132,  0.68825711, -0.3003827 ,
         1.        ]])